spring.application.name=personal-assistant
spring.data.mongodb.uri=${dburl}
spring.data.mongodb.database=personal-assistant
server.port=8080

#telegram bot configuration
telegram.bot.username=apna_dogesh_bot
telegram.bot.token=${token}

spring.quartz.job-store-type=memory
spring.quartz.auto-startup=true
logging.level.org.springframework=warn
logging.level.com.personalassistant=debug
logging.level.org.telegram=warn
logging.level.org.mongodb=warn
logging.level.org.quartz=warn
logging.level.org.apache=warn

gemini.api.key=${geminiApiKey}
weather.api.key=${weatherApiKey}
news.api.key=${newsApiKey}

webhook.url=${webHookUrl}

#1 ollama_connection (local Pc)
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text

# future enhancement: multiple model support
#spring.ai.ollama.chat.model=llama3


# 2. Vector Store (MongoDB Atlas)
#collection name jisme data store hoga
spring.ai.vectorstore.mongodb.collection-name=vector_store
#'Search Index Name'
spring.ai.vectorstore.mongodb.vector-index-name=vector_index

# Isse Spring AI khud table/collection bana lega
spring.ai.vectorstore.chroma.initialize-schema=true


#Groq api key
groq.api.key=${groqApiKey}
groq.model=llama-3.3-70b-versatile


