spring.application.name=personal-assistant
spring.data.mongodb.uri=${dburl}
spring.data.mongodb.database=personal-assistant
server.port=8080

//telegram bot configuration
telegram.bot.username=apna_dogesh_bot
telegram.bot.token=${token}

spring.quartz.job-store-type=memory
spring.quartz.auto-startup=true
logging.level.org.springframework=warn
logging.level.com.personalassistant=debug
logging.level.org.telegram=warn
logging.level.org.mongodb=warn
logging.level.org.quartz=warn
logging.level.org.apache=warn

gemini.api.key=${geminiApiKey}
weather.api.key=${weatherApiKey}
news.api.key=${newsApiKey}

webhook.url=${webHookUrl}

